install.packages("versions")
library("versions")
install.versions(c('shiny'), c('1.4.0.2'))
install.versions(c('shinyalert'), c('2.0.0'))
install.versions(c('shinyTime'), c('1.0.1'))
install.versions(c('shinyWidgets'), c('0.5.4'))
install.versions(c('plotly'), c('4.9.2.1'))
install.versions(c('lubridate'), c('1.7.8'))
install.versions(c('dplyr'), c('0.8.5'))
install.versions(c('tidyr'), c('1.0.2'))
install.versions(c('data.table'), c('1.12.8'))
install.versions(c('shinycssloaders'), c('1.0.0'))
install.versions(c('shinyFiles'), c('0.8.0'))
install.versions(c('shinyjs'), c('2.0.0'))
install.versions(c('fasttime'), c('1.0-2'))
install.versions(c('DT'), c('0.16'))
install.versions(c('suncalc'), c('0.5.0'))
install.versions(c('ggmap'), c('3.0.0'))
install.versions(c('measurements'), c('1.4.0'))
install.versions(c('assertthat'), c('0.2.1'))
install.versions(c('geosphere'), c('1.5-10'))
install.versions(c('swfscMisc'), c('1.3'))
install.versions(c('padr'), c('0.5.1'))
install.versions(c('sqldf'), c('0.4-11'))
install.versions(c('gridExtra'), c('2.3'))
install.versions(c('rjson'), c('0.2.20'))
install.versions(c('R6'), c('2.5.0'))