install.packages("versions")
install.packages("logging")
library("versions")
install_type = 'binary'
install.versions(c('shiny'), c('1.4.0.2'), type=install_type)
install.versions(c('shinyalert'), c('2.0.0'), type=install_type)
install.versions(c('shinyTime'), c('1.0.1'), type=install_type)
install.versions(c('shinyWidgets'), c('0.5.4'), type=install_type)
install.versions(c('plotly'), c('4.9.2.1'), type=install_type)
install.versions(c('lubridate'), c('1.7.8'), type=install_type)
install.versions(c('dplyr'), c('0.8.5'), type=install_type)
install.versions(c('tidyr'), c('1.0.2'), type=install_type)
install.versions(c('data.table'), c('1.12.8'), type=install_type)
install.versions(c('shinycssloaders'), c('1.0.0'), type=install_type)
install.versions(c('shinyFiles'), c('0.8.0'), type=install_type)
install.versions(c('shinyjs'), c('2.0.0'), type=install_type)
install.versions(c('fasttime'), c('1.0-2'), type=install_type)
install.versions(c('DT'), c('0.16'), type=install_type)
install.versions(c('suncalc'), c('0.5.0'), type=install_type)
install.versions(c('ggmap'), c('3.0.0'), type=install_type)
install.versions(c('measurements'), c('1.4.0'), type=install_type)
install.versions(c('assertthat'), c('0.2.1'), type=install_type)
install.versions(c('geosphere'), c('1.5-10'), type=install_type)
install.versions(c('swfscMisc'), c('1.3'), type=install_type)
install.versions(c('padr'), c('0.5.1'), type=install_type)
install.versions(c('sqldf'), c('0.4-11'), type=install_type)
install.versions(c('gridExtra'), c('2.3'), type=install_type)
install.versions(c('rjson'), c('0.2.20'), type=install_type)
install.versions(c('R6'), c('2.5.0'), type=install_type)