---
title: "Database interface user guide"
author: "Nick Gorman"
date: "7 July 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting started

To use the database interface we need to source the file containing it.

```{R, message=FALSE}
source("R/interface.R")
```

### Creating a sqlite database from solar analytics data.

Define the paths of the solar analytics files to use in the database.

```{r}
timeseries_path_name <- "tests/testthat/data/simple_timeseries.csv"
site_details_path_name <- "tests/testthat/data/simple_site_details.csv"
circuit_details_path_name <- "tests/testthat/data/simple_circuit_details.csv"
```

Create an instance of the database interface and use it to create a new database.

```{r}

dp <- DBInterface$new()

dp$connect_to_new_database("example_database.db")
```

Add the solar analytics data to the new database.

```{r, warning=FALSE}
dp$build_database(timeseries=timeseries_path_name,
                  circuit_details=circuit_details_path_name,
                  site_details=site_details_path_name)
```

