testthat::context("Test creating voltage KML function.")

test_that("Test creating voltage KML", {
  data <- read.csv("voltage.csv", sep=",")
  expected_result = paste(
    c(
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
      "<kml xmlns=\"http://www.opengis.net/kml/2.2\">",
      "  <Document>",
      "    <Style id=\"110kV\">",
      "      <LabelStyle>",
      "        <color>ff0000ff</color>",
      "        <width>1.3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"132kV\">",
      "      <LabelStyle>",
      "        <color>ff0000ff</color>",
      "        <width>1.3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"275kV\">",
      "      <LabelStyle>",
      "        <color>ffff00aa</color>",
      "        <width>3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"66kV\">",
      "      <LabelStyle>",
      "        <color>ff1872cc</color>",
      "        <width>1.3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"33kV\">",
      "      <LabelStyle>",
      "        <color>ff00aa00</color>",
      "        <width>1.3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"22kV\">",
      "      <LabelStyle>",
      "        <color>ffffaa55</color>",
      "        <width>1.3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"11kV\">",
      "      <LabelStyle>",
      "        <color>ffffaa55</color>",
      "        <width>1.3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"220kV\">",
      "      <LabelStyle>",
      "        <color>ffff0000</color>",
      "        <width>2</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"330kV\">",
      "      <LabelStyle>",
      "        <color>ff00aaff</color>",
      "        <width>3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"400kV\">",
      "      <LabelStyle>",
      "        <color>ffffaa55</color>",
      "        <width>3</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Style id=\"500kV\">",
      "      <LabelStyle>",
      "        <color>ff00ffff</color>",
      "        <width>4</width>",
      "      </LabelStyle>",
      "    </Style>",
      "    <Placemark>",
      "      <name>Central Label</name>",
      "      <description>Voltage: 500kV</description>",
      "      <styleUrl>#500kV</styleUrl>",
      "      <Point>",
      "        <coordinates>151.29,-33.86</coordinates>",
      "      </Point>",
      "    </Placemark>",
      "    <Placemark>",
      "      <name>South West Sydney</name>",
      "      <description>Voltage: 120kV</description>",
      "      <styleUrl>#120kV</styleUrl>",
      "      <Point>",
      "        <coordinates>151.09,-33.96</coordinates>",
      "      </Point>",
      "    </Placemark>",
      "  </Document>",
      "</kml>"
    ),
    collapse="\n"
  )
  result <- create_voltage_kml(data)
  testthat::expect_equivalent(result, expected_result)
})
